#   consul服务端口号
server:
  port: 8006
spring:
  application:
    name: cloud-providerconsul-payment
#    consul注册中心地址
  cloud:
    consul:
#      ip地址
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}

